/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentación;

import Entidades.Productora;
import Negocio.EliminarObjeto;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Gorte
 */
public class EliminarProductora extends javax.swing.JFrame {

    Productora[] productoras;
    ProductoraTableModel tableModelProductora;
    MenuPrincipal menuPrincipal;
    /**
     * Creates new form EliminarProductora
     * @param menuPrincipal
     * @param productoras
     * @throws Negocio.ExcepcionPersonalizada
     */
    public EliminarProductora(MenuPrincipal menuPrincipal,Productora[] productoras) throws Negocio.ExcepcionPersonalizada {
        if (productoras == null){
            throw new Negocio.ExcepcionPersonalizada ("No hay productoras registradas"); 
        }
        initComponents();
        this.productoras = productoras;
        this.menuPrincipal = menuPrincipal;
        try {
            addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {
                    menuPrincipal.setEliminarProductoraBtnEnabled(true);

                }
            });
            RefrescarProductoras(productoras);
        }
        catch (Negocio.ExcepcionPersonalizada e) {
            throw new Negocio.ExcepcionPersonalizada(e.getMessage());
        }
    }
    
    public void RefrescarProductoras (Productora[] productoras) throws Negocio.ExcepcionPersonalizada{
        try{
            tableModelProductora = new ProductoraTableModel(productoras);
            TblProductoras.setModel(tableModelProductora);
        }
        catch (Negocio.ExcepcionPersonalizada e) {
            JOptionPane.showMessageDialog(this, "No se puede actualizar la tabla de productoras: " + e.getMessage(), "Error", JOptionPane.WARNING_MESSAGE);
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "No se puede actualizar la tabla de productoras", "Error", JOptionPane.ERROR_MESSAGE);
        } 
    }
    private void limpiarProductora (){
        TblProductoras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Descripción"
            }
        ));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Regresar = new javax.swing.JButton();
        PnlEliminarProductora = new javax.swing.JPanel();
        ScrProductoras = new javax.swing.JScrollPane();
        TblProductoras = new javax.swing.JTable();
        BtnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Eliminar productora");
        setName(""); // NOI18N
        setResizable(false);

        Regresar.setBackground(new java.awt.Color(255, 204, 204));
        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        TblProductoras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Descripción"
            }
        ));
        ScrProductoras.setViewportView(TblProductoras);

        BtnEliminar.setForeground(new java.awt.Color(255, 51, 51));
        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlEliminarProductoraLayout = new javax.swing.GroupLayout(PnlEliminarProductora);
        PnlEliminarProductora.setLayout(PnlEliminarProductoraLayout);
        PnlEliminarProductoraLayout.setHorizontalGroup(
            PnlEliminarProductoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlEliminarProductoraLayout.createSequentialGroup()
                .addGroup(PnlEliminarProductoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlEliminarProductoraLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(ScrProductoras, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnlEliminarProductoraLayout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(BtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        PnlEliminarProductoraLayout.setVerticalGroup(
            PnlEliminarProductoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlEliminarProductoraLayout.createSequentialGroup()
                .addComponent(ScrProductoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Regresar))
                    .addComponent(PnlEliminarProductora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PnlEliminarProductora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Regresar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_RegresarActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        try {
            if (productoras[productoras.length-1].getPeliculas() != null){                
                if (productoras[productoras.length-1].getPeliculas()[0] != null) {
                    throw new Negocio.ExcepcionPersonalizada("La productura tiene peliculas registradas");                   
                }
            }
            productoras = menuPrincipal.DeleteProductora();
            if (productoras != null && productoras.length != 0){
               RefrescarProductoras(productoras); 
            }
            else {
                limpiarProductora();
            }            
        }
        catch (Negocio.ExcepcionPersonalizada e) {
            JOptionPane.showMessageDialog(this, "No se puede eliminar productoras: " + e.getMessage(), "Error", JOptionPane.WARNING_MESSAGE);
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "No se elimino la productoras por un error " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JPanel PnlEliminarProductora;
    private javax.swing.JButton Regresar;
    private javax.swing.JScrollPane ScrProductoras;
    private javax.swing.JTable TblProductoras;
    // End of variables declaration//GEN-END:variables
}
