/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentación;

import Entidades.Pelicula;
import Entidades.Productora;
import Negocio.EliminarObjeto;
import Negocio.ExcepcionPersonalizada;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Gorte
 */
public class EliminarPeliculas extends javax.swing.JFrame {
    
    Productora[] productoras;
    ProductoraTableModel tableModelProductora;
    PeliculaTableModel tableModelPelicula;
    /**
     * Creates new form EliminarPeliculas
     * @param menuPrincipal
     * @param productoras
     * @throws Negocio.ExcepcionPersonalizada
     */
    public EliminarPeliculas(MenuPrincipal menuPrincipal,Productora[] productoras) throws Negocio.ExcepcionPersonalizada {
        if (productoras == null){
            throw new Negocio.ExcepcionPersonalizada ("No hay productoras registradas"); 
        }
        initComponents();
        this.productoras = productoras;
        try {
            addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {
                    menuPrincipal.setEliminarPeliculasBtnEnabled(true);

                }
            });
            RefrescarProductoras(productoras);
        }
        catch (ExcepcionPersonalizada e) {
            throw new Negocio.ExcepcionPersonalizada(e.getMessage());
        }
    }
    private void limpiarPeliculas (){
        TblPeliculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Género", "Tipo de audiencia"
            }
        ));
    }
    public void RefrescarPeliculas (Pelicula[] peliculas) throws java.lang.Exception{
        try{
            tableModelPelicula = new PeliculaTableModel(peliculas);
            TblPeliculas.setModel(tableModelPelicula);
        }
        catch (Exception e){
            throw new Exception(e.getMessage());
        }
    }
    
    public void RefrescarProductoras (Productora[] productoras) throws Negocio.ExcepcionPersonalizada{
        Productora[] productorasOrigen;
        int ProductorasNoVacias = 0;
        for (Productora productora : productoras) {
            if (productora.getPeliculas() != null) {
                ProductorasNoVacias++;
            }
        }
        if (ProductorasNoVacias > 0){
            productorasOrigen = new Productora[ProductorasNoVacias];
            int contador = 0;
            for (Productora productora : productoras) {
                if (productora.getPeliculas() != null) {
                    productorasOrigen[contador] = productora;
                    contador++;
                }
            }
         
            try{
                tableModelProductora = new ProductoraTableModel(productorasOrigen);
                TblProductoras.setModel(tableModelProductora);
            }
            catch (Negocio.ExcepcionPersonalizada e) {
                JOptionPane.showMessageDialog(this, "No se puede abrir opción de registrar películas: " + e.getMessage(), "Error", JOptionPane.WARNING_MESSAGE);
            }
            catch (Exception e){
                JOptionPane.showMessageDialog(this, "No se puede actualizar la tabla de productoras", "Error", JOptionPane.ERROR_MESSAGE);
            } 
        }
    }
    private Productora obtenerValorSeleccionadoProductora(Productora[] productorasSelect) throws java.lang.Exception {
        int selectedRow = TblProductoras.getSelectedRow();

        try {
            int selectedValue = Integer.parseInt(String.valueOf(TblProductoras.getValueAt(selectedRow, 0)));
            return productorasSelect[selectedValue-1];            
        }
        catch (NumberFormatException e) {
            throw Exception (e.getMessage());
        }
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnRegresar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        BtnEliminar = new javax.swing.JButton();
        ScrProductoras = new javax.swing.JScrollPane();
        TblProductoras = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblPeliculas = new javax.swing.JTable();
        LblProductoras = new javax.swing.JLabel();
        LblPeliculas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Eliminar película");
        setResizable(false);

        BtnRegresar.setBackground(new java.awt.Color(255, 204, 204));
        BtnRegresar.setText("Regresar");
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });

        BtnEliminar.setForeground(new java.awt.Color(255, 51, 51));
        BtnEliminar.setText("Eliminar");
        BtnEliminar.setToolTipText("");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        TblProductoras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Descripción"
            }
        ));
        TblProductoras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SeleccionProductora(evt);
            }
        });
        ScrProductoras.setViewportView(TblProductoras);

        TblPeliculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Género", "Tipo de audiencia"
            }
        ));
        TblPeliculas.setToolTipText("");
        jScrollPane1.setViewportView(TblPeliculas);

        LblProductoras.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LblProductoras.setText("Productoras:");

        LblPeliculas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LblPeliculas.setText("Películas:");
        LblPeliculas.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrProductoras, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblProductoras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LblPeliculas)
                        .addGap(477, 477, 477))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(BtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(425, 425, 425)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblProductoras)
                    .addComponent(LblPeliculas))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addComponent(BtnEliminar)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ScrProductoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(991, Short.MAX_VALUE)
                        .addComponent(BtnRegresar))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnRegresar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnRegresarActionPerformed

    private void SeleccionProductora(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SeleccionProductora
        try {
            Productora productoraSelec = obtenerValorSeleccionadoProductora(productoras);
            RefrescarPeliculas(productoraSelec.getPeliculas());
        }
        catch (Exception e){
            limpiarPeliculas();
            JOptionPane.showMessageDialog(this, "No se puede mostar películas", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_SeleccionProductora

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        try {
            Productora productoraSelec = obtenerValorSeleccionadoProductora(productoras);
            productoraSelec.setPeliculas(EliminarObjeto.EliminarObjeto(productoraSelec.getPeliculas()));
            if (productoraSelec.getPeliculas() != null && productoraSelec.getPeliculas().length != 0){
               RefrescarPeliculas(productoraSelec.getPeliculas()); 
            }
            else {
                limpiarPeliculas();
            }
            RefrescarProductoras(productoras);
        }
        catch (Negocio.ExcepcionPersonalizada e) {
            JOptionPane.showMessageDialog(this, "No se puede eliminar películas: " + e.getMessage(), "Error", JOptionPane.WARNING_MESSAGE);
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "No se elimino la pelicula por un error verifique que selecciono alguna productora", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnEliminarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JLabel LblPeliculas;
    private javax.swing.JLabel LblProductoras;
    private javax.swing.JScrollPane ScrProductoras;
    private javax.swing.JTable TblPeliculas;
    private javax.swing.JTable TblProductoras;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private Exception Exception(String message) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
