/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentación;

import Entidades.Productora;
import java.awt.event.ActionEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Gorte
 */
public class MostrarPeliculas extends javax.swing.JFrame {
    
    MenuPrincipal menuPrincipal;
    ProductoraTableModel tableModel;
    RegistrarPelicula registrarPelicula;
    /**
     * Creates new form MostrarProductoras
     * @param menuPrincipal
     * @param productoras
     * @throws java.lang.Exception
     */
    public MostrarPeliculas(MenuPrincipal menuPrincipal, Productora[] productoras) throws Exception {
        initComponents();
        this.menuPrincipal = menuPrincipal;
        try {
            addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {
                    menuPrincipal.setRegistroPeliculasBtnEnabled(true);

                }
            });
            RefrescarProductoras(productoras);
        }
        catch (Exception e) {
            throw new Exception(e.getMessage());
        }
        
        BtnRegistar.addActionListener((ActionEvent e) -> {
            if (registrarPelicula == null || !registrarPelicula.isDisplayable()) {
                try {
                    if (obtenerValorSeleccionado(productoras) != null){
                        registrarPelicula = new RegistrarPelicula(MostrarPeliculas.this, obtenerValorSeleccionado(productoras));
                        registrarPelicula.setVisible(true);
                        BtnRegistar.setEnabled(false);
                    }
                }
                catch (Exception ex){
                    JOptionPane.showMessageDialog(this, "Error con la información de la productora brindada.", "Error", JOptionPane.ERROR_MESSAGE);
                }
                
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlMostrarProductoras = new javax.swing.JPanel();
        SpnMostrarProductoras = new javax.swing.JScrollPane();
        TblProductoras = new javax.swing.JTable();
        BtnRegresar = new javax.swing.JButton();
        BtnRegistar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mostrar peliculas");
        setResizable(false);

        TblProductoras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Descripcion"
            }
        ));
        SpnMostrarProductoras.setViewportView(TblProductoras);

        javax.swing.GroupLayout PnlMostrarProductorasLayout = new javax.swing.GroupLayout(PnlMostrarProductoras);
        PnlMostrarProductoras.setLayout(PnlMostrarProductorasLayout);
        PnlMostrarProductorasLayout.setHorizontalGroup(
            PnlMostrarProductorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlMostrarProductorasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SpnMostrarProductoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PnlMostrarProductorasLayout.setVerticalGroup(
            PnlMostrarProductorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlMostrarProductorasLayout.createSequentialGroup()
                .addComponent(SpnMostrarProductoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        BtnRegresar.setBackground(new java.awt.Color(255, 204, 204));
        BtnRegresar.setText("Regresar");
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });

        BtnRegistar.setBackground(new java.awt.Color(204, 255, 255));
        BtnRegistar.setText("Registrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnRegresar))
                    .addComponent(PnlMostrarProductoras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(BtnRegistar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PnlMostrarProductoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnRegistar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnRegresar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnRegresarActionPerformed
    
    public void AgregarPeliculas (Productora productora){
        menuPrincipal.AddPelicula(productora);
    }
    
    public void setRegistroPeliculaBtnEnabled(boolean enabled) {
        BtnRegistar.setEnabled(enabled);
    }
    
    public void LimpiarTabla () {
        TblProductoras.removeAll();
    }
    
    public void RefrescarProductoras (Productora[] productoras){
        try{
            tableModel = new ProductoraTableModel(productoras);
            TblProductoras.setModel(tableModel);
        }
        catch (Negocio.ExcepcionPersonalizada e) {
            JOptionPane.showMessageDialog(this, "No se puede abrir opción de registrar películas: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "No se puede actualizar la tabla de productoras", "Error", JOptionPane.ERROR_MESSAGE);
        } 
    }

    private Productora obtenerValorSeleccionado(Productora[] productorasSelect) throws java.lang.Exception {
        int selectedRow = TblProductoras.getSelectedRow();
               
        try {
            int selectedValue = Integer.parseInt(String.valueOf(TblProductoras.getValueAt(selectedRow, 0)));
            return productorasSelect[selectedValue-1];            
        }
        catch (NumberFormatException e) {
            throw new NumberFormatException (e.getMessage());
        }
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegistar;
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JPanel PnlMostrarProductoras;
    private javax.swing.JScrollPane SpnMostrarProductoras;
    private javax.swing.JTable TblProductoras;
    // End of variables declaration//GEN-END:variables

    private Exception Exception(String message) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
