/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentación;

import Entidades.Pelicula;
import Entidades.Productora;
import java.awt.HeadlessException;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.UUID;
import javax.swing.JOptionPane;

/**
 *
 * @author Gorte
 */
public class RegistrarPelicula extends javax.swing.JFrame {
    
    MostrarPeliculas mostrarPeliculas;
    private Productora productora;
    /**
     * Creates new form RegistrarPelicula
     * @param mostrarPeliculas
     * @param productora
     */
    public RegistrarPelicula(MostrarPeliculas mostrarPeliculas, Productora productora) {
        initComponents();
        try {
            this.mostrarPeliculas = mostrarPeliculas;
            this.productora = productora;
            addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {
                    mostrarPeliculas.setRegistroPeliculaBtnEnabled(true);

                }
            });
            if (productora == null){
                this.dispose();
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se puede abrir opción de registrar películas", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnRegresar = new javax.swing.JButton();
        PnlRegistrarPelicula = new javax.swing.JPanel();
        LblNombre = new javax.swing.JLabel();
        TxfNombre = new javax.swing.JTextField();
        LblGenero = new javax.swing.JLabel();
        CmbGenero = new javax.swing.JComboBox<>();
        LblTipo = new javax.swing.JLabel();
        CmbTipo = new javax.swing.JComboBox<>();
        BtnRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar películas");
        setResizable(false);

        BtnRegresar.setBackground(new java.awt.Color(255, 204, 204));
        BtnRegresar.setText("Regresar");
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });

        LblNombre.setText("Nombre:");

        LblGenero.setText("Genero película:");

        CmbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acción", "Aventura", "Catástrofe", "Ciencia Ficción", "Comedia", "Documental", "Drama", "Fantasía", "Musical", "Suspenso", "Terror" }));

        LblTipo.setText("Tipo de audiencia:");

        CmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Infantiles", "Juveniles", "Adultos", "Familiares" }));

        BtnRegistrar.setBackground(new java.awt.Color(204, 255, 255));
        BtnRegistrar.setText("Registrar");
        BtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlRegistrarPeliculaLayout = new javax.swing.GroupLayout(PnlRegistrarPelicula);
        PnlRegistrarPelicula.setLayout(PnlRegistrarPeliculaLayout);
        PnlRegistrarPeliculaLayout.setHorizontalGroup(
            PnlRegistrarPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlRegistrarPeliculaLayout.createSequentialGroup()
                .addGroup(PnlRegistrarPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlRegistrarPeliculaLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(PnlRegistrarPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlRegistrarPeliculaLayout.createSequentialGroup()
                                .addComponent(LblTipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlRegistrarPeliculaLayout.createSequentialGroup()
                                .addComponent(LblNombre)
                                .addGap(18, 18, 18)
                                .addComponent(TxfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlRegistrarPeliculaLayout.createSequentialGroup()
                                .addComponent(LblGenero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CmbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PnlRegistrarPeliculaLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(BtnRegistrar)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        PnlRegistrarPeliculaLayout.setVerticalGroup(
            PnlRegistrarPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlRegistrarPeliculaLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(PnlRegistrarPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblNombre)
                    .addComponent(TxfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(PnlRegistrarPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblGenero)
                    .addComponent(CmbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(PnlRegistrarPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblTipo)
                    .addComponent(CmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addComponent(BtnRegistrar))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnRegresar))
                    .addComponent(PnlRegistrarPelicula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PnlRegistrarPelicula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnRegresar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnRegresarActionPerformed

    private void BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarActionPerformed
        if (TxfNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Favor verificar los datos brindados", "Datos pendientes", JOptionPane.WARNING_MESSAGE);
            TxfNombre.requestFocus();
            return;
        }
        try {
            String DNI = generateDNI(); // Asignar un ID secuencial;
            String Nombre = TxfNombre.getText();
            String Genero =(String) CmbGenero.getSelectedItem();
            String Tipo =(String) CmbTipo.getSelectedItem() ;
            
            Pelicula peliculaAdd = new Pelicula( DNI, Nombre, Genero, Tipo);
        
            productora.setPeliculas(new Negocio.AgregarPelicula().AgregarPelicula(productora.getPeliculas(), peliculaAdd));
            
            mostrarPeliculas.AgregarPeliculas(productora);
            
            //JOptionPane.showMessageDialog(this, "Pelicula agregada ID: " + peliculaAdd.getDNI() + "\n" + peliculaAdd.getNombre(), "Información", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }
        catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error en los datos brindados", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnRegistrarActionPerformed

    private String generateDNI() {
        // Generar un UUID
        UUID uuid = UUID.randomUUID();
        
        // Convertir UUID a cadena
        return uuid.toString();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegistrar;
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JComboBox<String> CmbGenero;
    private javax.swing.JComboBox<String> CmbTipo;
    private javax.swing.JLabel LblGenero;
    private javax.swing.JLabel LblNombre;
    private javax.swing.JLabel LblTipo;
    private javax.swing.JPanel PnlRegistrarPelicula;
    private javax.swing.JTextField TxfNombre;
    // End of variables declaration//GEN-END:variables
}
