/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentasion;

import Negocio.CustomDocumentFilter;
import Entidades.Impresora;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author Gorte
 */
public class Insertar extends javax.swing.JFrame {

    MenuPrincipal menuPrincipal;
    /**
     * Creates new form Insertar
     * @param menuPrincipal
     */
    public Insertar(MenuPrincipal menuPrincipal) {
        initComponents();
        this.menuPrincipal = menuPrincipal;
        addWindowListener(new WindowAdapter() {                        
            @Override                
            public void windowClosed(WindowEvent e) {            
                menuPrincipal.setInsertarBtnEnabled(true);                
            }            
        });
        AbstractDocument documentSoloDigitos = (AbstractDocument) TxfPeso.getDocument();
        documentSoloDigitos.setDocumentFilter(new CustomDocumentFilter(text -> {
            if (text.length() > 4) {
                return false;
            }
            try {
                int number = Integer.parseInt(text);
                return number >= 0 && number <= 9999;
            } catch (NumberFormatException e) {
                return false;
            }
        }));
        AbstractDocument documentIDDigitos = (AbstractDocument) TxfID.getDocument();
        documentIDDigitos.setDocumentFilter(new CustomDocumentFilter(text -> {
            if (text.length() > 4) {
                return false;
            }
            try {
                int number = Integer.parseInt(text);
                return number >= 0 && number <= 9999;
            } catch (NumberFormatException e) {
                return false;
            }
        }));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnRegresar = new javax.swing.JButton();
        PnlFormulario = new javax.swing.JPanel();
        LblMarca = new javax.swing.JLabel();
        TxfMarca = new javax.swing.JTextField();
        LblTipo = new javax.swing.JLabel();
        CmbTipo = new javax.swing.JComboBox<>();
        LblPeso = new javax.swing.JLabel();
        TxfPeso = new javax.swing.JTextField();
        BtnInsertar = new javax.swing.JButton();
        LblKg = new javax.swing.JLabel();
        LblID = new javax.swing.JLabel();
        TxfID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        BtnRegresar.setBackground(new java.awt.Color(255, 204, 204));
        BtnRegresar.setLabel("Regresar");
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });

        LblMarca.setText("Marca:");

        LblTipo.setText("Tipo de impresora:");

        CmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Láser", "Inyección de tinta", "Matriz de puntos", "3D" }));

        LblPeso.setText("Peso:");

        BtnInsertar.setBackground(new java.awt.Color(204, 255, 255));
        BtnInsertar.setText("Registrar impresora");
        BtnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInsertarActionPerformed(evt);
            }
        });

        LblKg.setText("kg");

        LblID.setText("ID:");

        javax.swing.GroupLayout PnlFormularioLayout = new javax.swing.GroupLayout(PnlFormulario);
        PnlFormulario.setLayout(PnlFormularioLayout);
        PnlFormularioLayout.setHorizontalGroup(
            PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFormularioLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnInsertar)
                    .addGroup(PnlFormularioLayout.createSequentialGroup()
                        .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LblPeso)
                            .addComponent(LblMarca)
                            .addComponent(LblTipo)
                            .addComponent(LblID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxfMarca)
                            .addComponent(CmbTipo, 0, 1, Short.MAX_VALUE)
                            .addComponent(TxfPeso, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addComponent(TxfID))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblKg)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        PnlFormularioLayout.setVerticalGroup(
            PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFormularioLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblID)
                    .addComponent(TxfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblMarca)
                    .addComponent(TxfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblTipo)
                    .addComponent(CmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblPeso)
                    .addComponent(TxfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblKg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(BtnInsertar)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnRegresar))
                    .addComponent(PnlFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PnlFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnRegresar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInsertarActionPerformed
        try {
            if (TxfMarca.getText().isEmpty() || TxfPeso.getText().isEmpty()) { 
                if (TxfMarca.getText().isEmpty()){
                  TxfMarca.requestFocusInWindow();  
                  
                }
                else {
                   TxfPeso.requestFocusInWindow(); 
                }  
                throw new Negocio.ExcepcionPersonalizada("Favor verificar los datos brindados");
            }
            int id = Integer.parseInt(TxfID.getText());
            String marca = TxfMarca.getText();
            String tipo = CmbTipo.getSelectedItem().toString();
            int peso = Integer.parseInt(TxfPeso.getText()); 
            Impresora impresora = new Impresora(id, marca, tipo, peso);
            menuPrincipal.agregarImpresora(impresora);
            this.dispose();
        }
        catch (Negocio.ExcepcionPersonalizada e) {
            JOptionPane.showMessageDialog(this, "No se puede registrar impresora: " + e.getMessage(), "Error", JOptionPane.WARNING_MESSAGE);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No se puede registrar impresora", "Error", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_BtnInsertarActionPerformed

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnInsertar;
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JComboBox<String> CmbTipo;
    private javax.swing.JLabel LblID;
    private javax.swing.JLabel LblKg;
    private javax.swing.JLabel LblMarca;
    private javax.swing.JLabel LblPeso;
    private javax.swing.JLabel LblTipo;
    private javax.swing.JPanel PnlFormulario;
    private javax.swing.JTextField TxfID;
    private javax.swing.JTextField TxfMarca;
    private javax.swing.JTextField TxfPeso;
    // End of variables declaration//GEN-END:variables
}
