/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentasion;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Gorte
 */
public class Recorrer extends javax.swing.JFrame {

    MenuPrincipal menuPrincipal;
    /**
     * Creates new form Graficacion
     * @param menuPrincipal
     */
    public Recorrer(MenuPrincipal menuPrincipal) {
        initComponents();
        this.menuPrincipal = menuPrincipal;
        addWindowListener(new WindowAdapter() {                        
            @Override                
            public void windowClosed(WindowEvent e) {            
                menuPrincipal.setrecorrerBtnEnabled(true);                
            }            
        });         
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnRegresar = new javax.swing.JButton();
        BtnPRE = new javax.swing.JButton();
        BtnPOST = new javax.swing.JButton();
        BtnIN = new javax.swing.JButton();
        LblPRE = new javax.swing.JLabel();
        LblPOST = new javax.swing.JLabel();
        LblIN = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mostrar orden");
        setResizable(false);

        BtnRegresar.setBackground(new java.awt.Color(255, 204, 204));
        BtnRegresar.setText("Regresar");
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });

        BtnPRE.setText("PRE-ORDEN");
        BtnPRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPREActionPerformed(evt);
            }
        });

        BtnPOST.setText("POST-ORDEN");
        BtnPOST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPOSTActionPerformed(evt);
            }
        });

        BtnIN.setText("IN-ORDEN");
        BtnIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnINActionPerformed(evt);
            }
        });

        LblPRE.setText("-");

        LblPOST.setText("-");

        LblIN.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnRegresar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnIN)
                                .addGap(28, 28, 28)
                                .addComponent(LblIN))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(BtnPRE)
                                    .addGap(18, 18, 18)
                                    .addComponent(LblPRE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(BtnPOST)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(LblPOST))))
                        .addGap(0, 378, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnPRE)
                    .addComponent(LblPRE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnPOST)
                    .addComponent(LblPOST))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnIN)
                    .addComponent(LblIN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(BtnRegresar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnRegresarActionPerformed

    private void BtnPREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPREActionPerformed
        try {
            String recorrido = menuPrincipal.recorrerArbol(2);
            
            LblPRE.setText(recorrido);
        }
        catch (Negocio.ExcepcionPersonalizada e) {
            JOptionPane.showMessageDialog(this, "No se puede mostrar recorrido: " + e.getMessage(), "Error", JOptionPane.WARNING_MESSAGE);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No se puede mostrar recorrido por un error no identificado", "Error", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_BtnPREActionPerformed

    private void BtnPOSTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPOSTActionPerformed
        try {
            String recorrido = menuPrincipal.recorrerArbol(1);
            
            LblPOST.setText(recorrido);
        }
        catch (Negocio.ExcepcionPersonalizada e) {
            JOptionPane.showMessageDialog(this, "No se puede mostrar recorrido: " + e.getMessage(), "Error", JOptionPane.WARNING_MESSAGE);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No se puede mostrar recorrido por un error no identificado", "Error", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_BtnPOSTActionPerformed

    private void BtnINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnINActionPerformed
        try {
            String recorrido = menuPrincipal.recorrerArbol(0);
            
            LblIN.setText(recorrido);
        }
        catch (Negocio.ExcepcionPersonalizada e) {
            JOptionPane.showMessageDialog(this, "No se puede mostrar recorrido: " + e.getMessage(), "Error", JOptionPane.WARNING_MESSAGE);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No se puede mostrar recorrido por un error no identificado", "Error", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_BtnINActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIN;
    private javax.swing.JButton BtnPOST;
    private javax.swing.JButton BtnPRE;
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JLabel LblIN;
    private javax.swing.JLabel LblPOST;
    private javax.swing.JLabel LblPRE;
    // End of variables declaration//GEN-END:variables

}
